platform :ios, '13.0'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

project 'testrn', {
  'Debug' => :debug,
  'Release' => :release,
}

target 'testrn' do
  config = use_native_modules!
  use_react_native!(
    :path => '../node_modules/react-native',
    :hermes_enabled => false
  )
  pod 'react-native-config', :path => '../node_modules/react-native-config'
  pod 'RNBootSplash', :path => '../node_modules/react-native-bootsplash'
end

post_install do |installer|
  react_native_post_install(installer)
end
